# Generated by Django 2.2.6 on 2020-03-18 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepersonrole',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_database.Movie'),
        ),
        migrations.AlterField(
            model_name='moviepersonrole',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_database.Person'),
        ),
    ]
